;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((projectile-project-compilation-cmd . "yarn build")))
 (js2-mode . ((flycheck-checker . javascript-eslint)
              (javascript-backend . 'lsp)
              (javascript-fmt-tool . 'prettier)
              (javascript-lsp-linter . nil)
              (js-basic-offset . 2)
              (js-indent-level . 2)
              (js2-basic-offset . 2)
              (js2-indent-level . 2)
              (js2-strict-missing-semi-warning . nil)
              (node-add-modules-path . t)))
 (json-mode . ((json-fmt-tool . 'prettier)
               (json-fmt-on-save . t)))
 (markdown-mode . ((sentence-end-double-space . t)))
 (typescript-mode . ((node-add-modules-path . t)
                     (typescript-backend . 'lsp)
                     (typescript-fmt-on-save . t)
                     (typescript-fmt-tool . 'prettier)
                     (typescript-linter . 'eslint)
                     (typescript-lsp-linter . nil)))
 (typescript-tsx-mode . ((node-add-modules-path . t)
                         (typescript-backend . 'lsp)
                         (typescript-fmt-on-save . t)
                         (typescript-fmt-tool . 'prettier)
                         (typescript-linter . 'eslint)
                         (typescript-lsp-linter . nil)
                         (web-mode-code-indent-offset . 2))))
